# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (optional, MCP may use stdio, so not exposing ports by default)

# Command to run the server
CMD ["node", "dist/src/server/index.js"]
